<a href="https://colab.research.google.com/github/madliners/sipocodingtrial/blob/main/Module_5B_Markov_Chain_Trial_Pam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Install Package

In [19]:
pip install mchmm

Clone dari Link Github yang Tersedia

In [20]:
!git clone https://github.com/maximtrp/mchmm.git
!cd mchmm
!pip install . --user

fatal: destination path 'mchmm' already exists and is not an empty directory.
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.


Gunakan Markov Chain dari Data yang Telah Tersedia

In [22]:
import mchmm as mc
a = mc.MarkovChain().from_data('ABBAACABCCBBCBAACAABBCABABABBCBCBCBAABBAAABCCBBBBAAACCCACACACCAAAABBABABAAACBCC')

In [23]:
a.observed_matrix

array([[13., 11.,  7.],
       [10.,  9.,  8.],
       [ 7.,  7.,  6.]])

Menggunakan Pandas dalam Anotasi Kolom dan Baris pada Matriks

In [24]:
import pandas as pd
pd.DataFrame(a.observed_matrix, index=a.states, columns=a.states, dtype=int)

A   B  C
A  13  11  7
B  10   9  8
C   7   7  6

Matriks Probabilitas Transisi

In [25]:
a.observed_p_matrix

array([[0.41935484, 0.35483871, 0.22580645],
       [0.37037037, 0.33333333, 0.2962963 ],
       [0.35      , 0.35      , 0.3       ]])

Visualisasi Rantai Markov

In [26]:
graph = a.graph_make(
      format="png",
      graph_attr=[("rankdir", "LR")],
      node_attr=[("fontname", "Roboto bold"), ("fontsize", "20")],
      edge_attr=[("fontname", "Iosevka"), ("fontsize", "12")]
    )
graph.render()

'Digraph.gv.png'

Ekspetasi Transisi Frekuensi

In [27]:
a.expected_matrix

array([[11.92307692, 10.73076923,  8.34615385],
       [10.38461538,  9.34615385,  7.26923077],
       [ 7.69230769,  6.92307692,  5.38461538]])

Menghitung Matriks Probabilitas Transisi Orde-8

In [28]:
a.n_order_matrix(a.observed_p_matrix, order=8)

array([[0.38365852, 0.34608827, 0.2702532 ],
       [0.38365852, 0.34608827, 0.2702532 ],
       [0.38365852, 0.34608827, 0.2702532 ]])

Mensimulasikan Rantai Markov

In [29]:
import numpy as np
ids, states = a.simulate(5, start='C', seed=np.random.randint(0,5,5))
ids

array([2, 2, 2, 0, 2])

In [30]:
states

array(['C', 'C', 'C', 'A', 'C'], dtype='<U1')

In [31]:
"".join(states)

'CCCAC'